
// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;

namespace TumorImageClassificationModel.ConsoleApp
{
    class Program
    {½
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            var imageBytes = File.ReadAllBytes(@"C:\Users\tobin\OneDrive\Skrivebord\Test billeder\brain-tumor-overview.jpg");
            //var imageBytes = File.ReadAllBytes(@"C:\Users\tobin\OneDrive\Skrivebord\MLProjectData\Brain Tumor Data Set\Brain Tumor Data Set\Healthy\Not Cancer  (7).jpg");
            TumorImageClassificationModel.ModelInput sampleData = new TumorImageClassificationModel.ModelInput()
            {
                ImageSource = imageBytes,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = TumorImageClassificationModel.Predict(sampleData);
            Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
        }
    }
}

