// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using TumorClassificationModel_WebApi;

// Configure app
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddPredictionEnginePool<TumorClassificationModel.ModelInput, TumorClassificationModel.ModelOutput>()
    .FromFile("TumorClassificationModel.zip");
builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Brain Tumor API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "Brain Tumor API V1");
});

// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<TumorClassificationModel.ModelInput, TumorClassificationModel.ModelOutput> predictionEnginePool, string imagePath) =>
    {
        var input = new TumorClassificationModel.ModelInput()
        {
            ImageSource = File.ReadAllBytes(imagePath),
        };

        return await Task.FromResult(predictionEnginePool.Predict(input));
    });

// Run app
app.Run();
